-- TODO Add support for other operations. For example:
-- Functions to add/del/list the GK FIB entries.
-- Functions to list the ARP table.
-- Functions to list the ND table.
-- Functions to process the GT policies.
-- ......
